import os
import json
import logging
from pathlib import Path
from pydantic import BaseModel, Field
from openai import OpenAI

# vLLM server đang chạy Qwen2.5-7B ở port 8000
LOCAL_API_BASE = "http://localhost:8000/v1"
LOCAL_API_KEY = "EMPTY"  
MODEL_NAME = "bartowski/Qwen2.5-7B-Instruct-GGUF"  

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class IndicatorContext(BaseModel):
    type: str = Field(description="The type of the indicator, usually 'Syscall' or 'Artifact'")
    api: str = Field(description="The API call or the file path dropping action")
    source_file: str = Field(description="Usually 'syscalls.log' or 'docker_diff'")
    package_name: str = Field(description="The name of the package")

class BehaviorDescription(BaseModel):
    name: str = Field(description="CamelCase description of the behavior (e.g., HiddenFileDrop, ReverseShell)")
    description: str = Field(description="Detailed explanation of what the intent behind this behavior is")

class MitreTechnique(BaseModel):
    id: str = Field(description="The MITRE ATT&CK Technique ID (e.g., T1059)")
    name: str = Field(description="The MITRE Technique Name")

class MitreTactic(BaseModel):
    id: str = Field(description="The MITRE ATT&CK Tactic ID (e.g., TA0002)")
    name: str = Field(description="The MITRE Tactic Name")

class ThreatNode(BaseModel):
    indicator: IndicatorContext
    behavior: BehaviorDescription
    technique: MitreTechnique
    tactic: MitreTactic

class ThreatExtractionResponse(BaseModel):
    threats: list[ThreatNode]

PROMPT_TEMPLATE = """<system>You are an elite Cyber Threat Intelligence Prosecutor and Forensic Analyst. Your absolute objective is to analyze dynamic system call (syscall) logs generated by a Python package and build a concrete, evidence-based indictment against malicious activities.
CRITICAL DIRECTIVES:
1. THE ANTI-NOISE PROTOCOL: You must entirely ignore background noise inherent to Python package compilation. Operations involving standard Python module loading, creating virtual environments, compiling C extensions (gcc, mpifort), and standard '/tmp/pip-req-build-*' or '/tmp/pip-install-*' activities are BENIGN. Do not report them.
2. HUNT FOR HARD COORDINATES: Never issue generic warnings (e.g., "suspicious file activity"). You MUST track the exact coordinates. Extract precise absolute file paths (e.g., '/tmp/miner.sh', '/etc/shadow', '~/.ssh/id_rsa') and exact Network IPs/Domains found in 'execve', 'openat', or 'connect' syscalls.
3. MITRE ATT&CK MAPPING: Every extracted threat MUST be explicitly mapped to the MITRE ATT&CK framework. You must categorize findings under specific Sub-Techniques (e.g., T1059.006 for Python execution, T1552.001 for credential reading).
4. HEURISTIC DETECTION RULES:
   - IF you observe 'mprotect' syscalls combined with network payload fetching, THEN report it as Fileless Memory Execution (T1055).
   - IF the package attempts to 'openat' or read '/.dockerenv', '/proc/meminfo', or similar environment files, THEN report it as Sandbox Evasion / System Information Discovery (T1082 / T1497).
   - IF the package reads '/root/.ssh/id_rsa', '/etc/shadow', or '/etc/passwd', THEN report it as Credential Access / Credential Theft (T1552/T1003).
   - IF you observe large-scale decoding, zlib decompress, or base64 manipulation immediately followed by 'execve' or 'os.system' equivalent syscalls, THEN report it as Obfuscated Payload Execution (T1027).
EXTRACTION WORKFLOW:
- Step 1: Analyze the <syscall_logs> for actions that clearly violate standard package installation boundaries (e.g., establishing reverse shells, executing multi-threaded payloads, dropping hidden binaries).
- Step 2: Formulate the 'BehaviorDescription'.
- Step 3: Populate the strict JSON schema. If NO malicious intent is found beyond reasonable doubt, return {"threats": []}. Do not hallucinate threats.</system>
<user>Target Package Name: {package_name}
<syscall_logs>
{log_content}
</syscall_logs>
Execute the extraction workflow and output strictly the final JSON matching the schema below. Do not include introductory text, explanations, or Markdown formatting (no ```json blocks). Output raw JSON only.
{
  "threats": [
    {
      "indicator": {
        "type": "Syscall or Artifact",
        "api": "The API call or the file path dropping action",
        "source_file": "syscalls.log or docker_diff",
        "package_name": "package_name"
      },
      "behavior": {
        "name": "CamelCase description (e.g., HiddenFileDrop)",
        "description": "Detailed explanation of malicious intent"
      },
      "technique": {
        "id": "TXXXX",
        "name": "MITRE Technique Name"
      },
      "tactic": {
        "id": "TAXXXX",
        "name": "MITRE Tactic Name"
      }
    }
  ]
}
</user>"""

def extract_threats_qwen(package_name, log_content):
    """Gọi Local Model (Qwen2.5-7B) để thực hiện Threat Extraction Prosecutor."""
    client = OpenAI(base_url=LOCAL_API_BASE, api_key=LOCAL_API_KEY)
    prompt = PROMPT_TEMPLATE.replace("{package_name}", package_name).replace("{log_content}", log_content)
    
    logging.info(f"Sending prompt to Prosecutor (Qwen2.5) for {package_name}...")
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "You are a Cyber Security Prosecutor. Extract malicious threats into strict JSON."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.1
        )
        
        raw_text = response.choices[0].message.content.strip()
        
        # Logic làm sạch chuỗi JSON phòng trường hợp model vẫn trả về markdown
        if raw_text.startswith("```json"):
            raw_text = raw_text[7:]
        elif raw_text.startswith("```"):
            raw_text = raw_text[3:]
            
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]
            
        raw_text = raw_text.strip()
        
        print(f"\n--- [DEBUG] RAW OUTPUT TỪ QWEN (Package: {package_name}) ---")
        print(raw_text)
        print("--------------------------------------------------------------\n")
        
        return json.loads(raw_text)
        
    except Exception as e:
        print(f"\n[CRASH LOG] 💥 LỖI QWEN (Crash): {e}\n")
        logging.error(f"Failed to process Local AI response: {e}")
        return {"threats": []}